/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fuzz.ssml.rest

import org.dom4j.DocumentHelper

enum class Language(val id: Int, val value: String) {
    ENU(0x0409,"en-us"),
    PTB(0x0416,"pt-br"),
    CHS(0x0804, "zh-cn"),
}

enum class Gender(val value: String) {
    FEMALE("Female"),
    MALE("Male"),
}

fun main(args: Array<String>) {
    println(ssml())
}

fun ssml(lang:String = Language.ENU.value,
         gender:String = Gender.FEMALE.value,
         name:String = "en-US-JessaNeural",
         text:String = "1: 23456. 789? 0!") :String {
    val document = DocumentHelper.createDocument()
    val speak = document.addElement("speak")
    speak.addAttribute("version", "1.0")
    speak.addAttribute("xml:lang", lang)
    val voice = speak.addElement("voice")
    voice.addAttribute("xml:lang", lang)
    voice.addAttribute("xml:gender", gender)
    voice.addAttribute("name", name)
    voice.addText(text)
    return document.asXML()
}
