/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fuzz.ssml.rest

import kotlin.test.*

class AppTest {
    @Test fun testSSML() {
        assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<speak version=\"1.0\" xml:lang=\"en-us\"><voice xml:lang=\"en-us\" xml:gender=\"Female\" name=\"en-US-JessaNeural\">1: 23456. 789? 0!</voice></speak>", ssml())
    }
}
